config/routes.rb
Rails.application.routes.draw do
  
  resources :books
  resources :authors

  resources :tags

  # root 'books#index'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    validates :name, presence: true
    validates :surname, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  validates :title, presence: true
  validates :author, presence: true
  validates :status, presence: true
  
  enum read_status: {queue: "queue desc", reading: "reading", suspended: "suspended", read: "read"} #, _prefix: :status
  STATUS_SELECT = read_statuses.map.with_index {|r, i| [r.second.to_s, i] }

  def status_desc
    Book.read_statuses.map {|r| [r] }[status].first.second.to_s
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :find_author, only: [:edit, :update, :show, :destroy]

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author saved"
      redirect_to authors_path
    else
      render action: 'new'
    end
  end

  def edit
    
  end

  def update
    if @author.update_attributes(author_params)      
      flash[:notice] = "Author changed"
      redirect_to authors_path
    else
      render action: 'edit'
    end
  end

  def index
    @authors = Author.all
  end

  def show
    
  end

  def destroy
    @author.destroy
    flash[:notice] = "Author deleted"
    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:name, :surname)
  end

  def find_author
    @author = Author.find(params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authors_all, only: [:show, :edit, :new]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show

  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.date_insert = DateTime.now.to_date
    @book.status=@book.status.to_i
    # @book.status = "queue"

    # respond_to do |format|
      if @book.save
        # format.html { redirect_to @book, notice: 'Book was successfully created.' }
        # format.json { render :show, status: :created, location: @book }
        flash[:notice] = "Book saved"
        redirect_to books_path
      else
        authors_all
        # format.html { render :new }
        # format.json { render json: @book.errors, status: :unprocessable_entity }        
        render action: 'new'
      end
    # end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    #@book.status = Book.read_statuses.index(@book.status).to_i

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def authors_all
      @authors = Author.all
    end

    def set_statuses
      @statuses = Book.status.map
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_id, :status, :why_want_read, :review, :raiting, :date_insert, :date_start_reading, :date_finish_reading)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, only: [:edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "Tag saved"
      redirect_to tags_path
    else
      render action: 'new'
    end
  end

  def edit
  
  end

  def update
    if @tag.update_attributes(tag_params)      
      flash[:notice] = "Tag changed"
      redirect_to tags_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @tag.destroy
    flash[:notice] = "Tag deleted"
    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

  def find_tag
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/authors/_form.html.erb
<% if @author.errors.present? %>
    <div class="alert alert-danger">
        <p>Errors:</p>
        <ol>
            <% @author.errors.full_messages.each do |message| %>
            <!--<li><%= message.titleize %></li> -->
            <li><%= message %></li>
            <% end %>
        </ol>
    </div>
<% end %>
<%= form_for @author do |f| %>
<div> 
    <%= f.label :name, "Name" %>
    <%= f.text_field :name , class: "form-control "%>
</div>
<div> 
    <%= f.label :name, "Surname" %>
    <%= f.text_field :surname , class: "form-control "%>
</div>
<div>
    <%= f.submit button_name, class: "btn btn-primary" %>
    <%= link_to "Cancel", authors_path, class: "btn btn-danger" %>
</div>
<% end %>

app/views/authors/edit.html.erb
<h3>Edit author</h3>
<%= render partial: "form", locals: { button_name: "Save changes" } %>

app/views/authors/index.html.erb
<h3>Authors</h3>

<p><%= link_to "New author", new_author_path, class: "btn btn-success" %> </p>

<table class="table table-stripped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    <% @authors.each do |author| %>
    <tr>
        <td><%= author.id %></td>
        <td><%= author.name %></td>
        <td><%= author.surname %></td>
        <td>
        <%= link_to "Show", author_path(author), class: "btn btn-default btn-xs" %>
        <%= link_to "Edit", edit_author_path(author), class: "btn btn-primary btn-xs" %>
        <%= link_to "Delete", author_path(author), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Are you sure?" } %>
        </td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/authors/new.html.erb
<h3>New author</h3>
<%= render partial: "form", locals: { button_name: "Save new" } %>

<%= link_to 'Back', books_path %>

app/views/authors/show.html.erb
<p><%= @author.name %></p>
<p><%= @author.surname %></p>

<p><%= link_to "Return", authors_path %></p>

app/views/books/_form.html.erb
<% if @book.errors.present? %>
    <div class="alert alert-danger">
        <p>Errors:</p>
        <ol>
            <% @book.errors.full_messages.each do |message| %>
            <!--<li><%= message.titleize %></li> -->
            <li><%= message %></li>
            <% end %>
        </ol>
    </div>
<% end %>

<%= form_for @book do |f| %>
  <div> 
      <%= f.label :title, "Title" %>
      <%= f.text_field :title , class: "form-control "%>
  </div>

  <div> 
      <%= f.label :author, "Author" %>
      <% if @book.author_id? %>      
        <%= f.select :author_id , @authors.map{ |a| [a.name + ' ' + a.surname, a.id]}, { }, class: "form-control " %>
      <% else %>
        <%= f.select :author_id, options_for_select(@authors.map{ |a| [a.name + ' ' + a.surname, a.id] }),  
             { :include_blank => 'Select a author' }, class: "form-control " %>
      <% end %>
  </div>

  <div> 
      <%= f.label :status, "Status" %>
      <% if @book.status? %>
        <%= f.select :status , Book.const_get(:STATUS_SELECT), { }, class: "form-control " %>
      <% else %>
        <%= f.select :status, Book.const_get(:STATUS_SELECT), 
            { :include_blank => 'Select a status' }, class: "form-control " %>
      <% end %>
  </div>

  <div> 
      <%= f.label :raiting, "Raiitng" %>
      <%= f.number_field :raiting, class: "form-control "%>
  </div>

   <div> 
      <%= f.label :why_want_read, "Why want read" %>
      <%= f.text_area :why_want_read, class: "form-control "%>
  </div>

   <div> 
      <%= f.label :date_start_reading, "Date start reading" %>
      <%= f.date_field :date_start_reading, :placeholder => 'yyyy-mm-dd', class: 'form-control datepicker' %>
  </div>

   <div> 
      <%= f.label :date_finish_reading, "Date finish reading" %>
      <%= f.date_field :date_finish_reading, :placeholder => 'yyyy-mm-dd', class: 'form-control datepicker' %>
  </div>

 <%= f.submit button_name, class: "btn btn-primary" %>
 <%= link_to 'Back', books_path, class: "btn btn-danger"  %>
 <% end %>

 <script>
 $( document ).ready(function() {
    $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
  });
</script>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render partial: "form", locals: { button_name: "Save changes", mode_edit: true } %>

<%= link_to 'Show', @book %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Books</h3>

<p><%= link_to "New book", new_book_path, class: "btn btn-success" %> </p>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Raiting</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author.name + ' ' + book.author.surname %></td>
        <td><%= book.status_desc %></td>
        <td><%= book.raiting %></td>
        <td>
        <%= link_to "Show", book_path(book), class: "btn btn-default btn-xs" %>
        <%= link_to "Edit", edit_book_path(book), class: "btn btn-primary btn-xs" %>
        <%= link_to "Delete", book_path(book), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<h3>New Book</h3>
<%= render partial: "form", locals: { button_name: "Save new", mode_edit: false } %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author.name + ' ' + @book.author.surname %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status_desc %>
</p>

<p>
  <strong>Why want read:</strong>
  <%= @book.why_want_read %>
</p>

<p>
  <strong>Review:</strong>
  <%= @book.review %>
</p>

<p>
  <strong>Raiting:</strong>
  <%= @book.raiting %>
</p>

<p>
  <strong>Date insert:</strong>
  <%= @book.date_insert %>
</p>

<p>
  <strong>Date start reading:</strong>
  <%= @book.date_start_reading %>
</p>

<p>
  <strong>Date finish reading:</strong>
  <%= @book.date_finish_reading %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice].present? %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <div class="page-header">
      <h1>Books</h1>
      </div>
      <%= yield %>    
    </div>
  </body>
</html>

app/views/tags/_form.html.erb
<% if @tag.errors.present? %>
    <div class="alert alert-danger">
        <p>Errors:</p>
        <ol>
            <% @tag.errors.full_messages.each do |message| %>
            <!--<li><%= message.titleize %></li> -->
            <li><%= message %></li>
            <% end %>
        </ol>
    </div>
<% end %>
<%= form_for @tag do |f| %>
<div> 
    <%= f.label :name, "Name" %>
    <%= f.text_field :name , class: "form-control "%>
</div>
<div>
    <%= f.submit button_name, class: "btn btn-primary" %>
    <%= link_to "Cancel", tags_path, class: "btn btn-danger" %>
</div>
<% end %>

app/views/tags/edit.html.erb
<h3>Edit tag</h3>
<%= render partial: "form", locals: { button_name: "Save changes" } %>

app/views/tags/index.html.erb
<h3>Tags</h3>

<p><%= link_to "New tag", new_tag_path, class: "btn btn-success" %> </p>

<table class="table table-stripped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
    <% @tags.each do |tag| %>
    <tr>
        <td><%= tag.id %></td>
        <td><%= tag.name %></td>
        <td>
        <%= link_to "Edit", edit_tag_path(tag), class: "btn btn-primary btn-xs" %>
        <%= link_to "Delete", tag_path(tag), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Are you sure?" } %>
        </td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/tags/new.html.erb
<h3>New tag</h3>
<%= render partial: "form", locals: { button_name: "Save new" } %>